esphome:
  name: esp01htu2x

esp8266:
  board: esp01_1m
#  framework:
#    type: esp-idf

deep_sleep:
  run_duration: 60s
  sleep_duration: 5min

wifi:
  ssid: !secret wifi_ssid_home
  password: !secret wifi_password_home
  reboot_timeout: 0s
  ap:
    ssid: "esp01htu2x1"
    password: !secret ap_password
    ap_timeout: 20s
#  power_save_mode: HIGH

#captive_portal:

# Enable logging
logger:
  #level: VERY_VERBOSE
  #level: INFO

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

# Активация web сервера
web_server:
  port: 80
  ota: false
  version: 1
  
i2c:
  sda: 0
  scl: 2
  scan: false
  id: bus_a
  frequency: 100kHz

# Individual sensors
sensor:   
  - platform: uptime
    name: Uptime Sensor

  - platform: htu21d  
    id: dt
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"

  - platform: adc
    id: vcc
    pin: VCC
    name: "VCC Voltage"

  - platform: wifi_signal
    id: wifi_s
    name: "WiFi Signal Sensor"    
