esphome:
  name: hall
  platformio_options:
    board_build.f_cpu: 80000000L

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    platform_version: 5.4.0
    version: 4.4.5

wifi:
  ssid: "Nadtocheeva 5"
  password: "123123123"
  reboot_timeout: 0s
  ap:
    ssid: "hall"
    password: "123123123"
    ap_timeout: 20s
#  power_save_mode: HIGH

#captive_portal:

# Enable logging
logger:
  #level: VERY_VERBOSE
  #level: INFO

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

# Активация web сервера
web_server:
  port: 80
#  local: true
  ota: false
  version: 2
  js_include: "www.js"
  js_url: ""

#status_led:
#  pin:
#    number: GPIO2
#    inverted: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    filters:
      - delayed_on: 50ms
    name: "Boot button"


# Individual sensors
sensor:   
  - platform: uptime
    name: Uptime Sensor
    update_interval: 5min

  - platform: esp32_hall
    name: "ESP32 Hall Sensor"
    update_interval: 100s

select:
  - platform: template
    name: Mode
    id: mode
    options:
      - "Option1"
      - "Option2"
      - "Option3"
#    initial_option: "OFF"
    optimistic: true
    set_action:
      - logger.log:
          format: "Chosen option: %s"
          args: ["x.c_str()"]

lock:
  - platform: template
    name: Lock comp
    optimistic: true
    on_lock:
    - logger.log: "Door Locked!"
    on_unlock:
    - logger.log: "Door Unlocked!"          

font:
  - file: "fonts/tahomabd.ttf"
    id: tahoma_clock
    size: 80
  - file: "fonts/tahomabd.ttf"
    id: tahoma_16
    size: 16

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13

display:
  - platform: st7567
    cs_pin: GPIO15
    dc_pin: GPIO27
    reset_pin: GPIO26
    lambda: |-
      it.line(0, 0, 127, 63);
      it.circle(64, 32, 20);

