esphome:
  name: regulator-vanna
  platformio_options:
    upload_speed: 460800
    board_build.f_cpu: 80000000L
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    platform_version: 5.4.0
    version: 4.4.5

wifi:
  ap:
    ssid: "Regulator-Vanna"
    password: "123123123"
  reboot_timeout: 0s
  power_save_mode: HIGH

# Enable logging
logger:
  #level: debug
  level: INFO

# Enable Home Assistant API
#api:

#ota:

# Активация web сервера
web_server:
  port: 80
  ota: false
  version: 2
  js_include: "www_all_number.js"
  js_url: ""

#status_led:
#  pin:
#    number: D1
#    inverted: no

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 50ms
    name: "Switch button"

dallas:
  - pin: GPIO10
    update_interval: 30s

# Individual sensors
sensor:   
  - platform: uptime
    name: Uptime Sensor
    update_interval: 5min

  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: dallas
    name: "Temperature"
    address: 0x7f04159053c4ff28
    id: temp_1
    on_value_range:
      - below: 38.0
        then:
          - light.turn_on:
              id: rgb_led
              brightness: 50%
              red: 0%
              green: 0%
              blue: 100%
      - above: 43.0
        below: 38.0
        then:
          - light.turn_on:
              id: rgb_led
              brightness: 50%
              red: 0%
              green: 100%
              blue: 0%
      - above: 43.0
        then:
          - light.turn_on:
              id: rgb_led
              brightness: 50%
              red: 100%
              green: 0%
              blue: 0%

switch:
  - platform: gpio
    pin:
       number: GPIO7
    id: relay1
    on_turn_on:
      - switch.turn_on: led1
    on_turn_off:
      - switch.turn_off: led1
  
  - platform: gpio
    pin:
      number: GPIO6
    id: relay_power

  - platform: gpio
    pin:
      number: GPIO18
    id: led1

  - platform: gpio
    pin:
      number: GPIO19
    id: led2

output:
  - platform: ledc
    pin: GPIO3
    id: out_red
  - platform: ledc
    pin: GPIO4
    id: out_green
  - platform: ledc
    pin: GPIO5
    id: out_blue

light:
  - platform: rgb
    id: rgb_led
    name: "RGB led"
    red: out_red
    green: out_green
    blue: out_blue

interval:
  - interval: 2sec
    then:
      light.toggle: rgb_led
        
climate:
  - platform: bang_bang
    name: "Bang Bang Climate Controller"
    sensor: temp_1
    default_target_temperature_low: 40 °C
    default_target_temperature_high: 40.5 °C
    id: regul
    heat_action:
      - switch.turn_on: relay1
      - switch.turn_on: relay_power
      - delay: 100ms
      - switch.turn_off: relay_power
    idle_action:
      - switch.turn_off: relay1
    visual:
      min_temperature: 30
      max_temperature: 43
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
         

