esphome:
  name: stairs

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid_home
  password: !secret wifi_password_home
  reboot_timeout: 0s
  ap:
    ssid: "stairs"
    password: !secret ap_password
    ap_timeout: 0s
  power_save_mode: HIGH

#captive_portal:

# Enable logging
logger:
  level: NONE

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

# Активация web сервера
web_server:
  port: 80
  ota: false
  version: 2
  #local: true
  js_include: "www_all_number.js"
  js_url: ""

# Individual sensors
sensor:
  - platform: uptime
    name: Uptime Sensor

  - platform: adc
    id: vcc
    pin: VCC
    name: "VCC Voltage"

  - platform: wifi_signal
    id: wifi_s
    name: "WiFi Signal Sensor"

i2c:
  frequency: 400kHz

pca9685:
  frequency: 1000Hz

output:
  - platform: pca9685
    channel: 0
    id: pwm01
  - platform: pca9685
    channel: 1
    id: pwm02
  - platform: pca9685
    channel: 2
    id: pwm03
  - platform: pca9685
    channel: 3
    id: pwm04
  - platform: pca9685
    channel: 4
    id: pwm05
  - platform: pca9685
    channel: 5
    id: pwm06
  - platform: pca9685
    channel: 6
    id: pwm07
  - platform: pca9685
    channel: 7
    id: pwm08
  - platform: pca9685
    channel: 8
    id: pwm09
  - platform: pca9685
    channel: 9
    id: pwm10
  - platform: pca9685
    channel: 10
    id: pwm11
  - platform: pca9685
    channel: 11
    id: pwm12
  - platform: pca9685
    channel: 12
    id: pwm13
  - platform: pca9685
    channel: 13
    id: pwm14
  - platform: pca9685
    channel: 14
    id: pwm15
  - platform: pca9685
    channel: 15
    id: pwm16

  - platform: gpio
    id: led_output
#status_led:
    pin:
      number: LED
      inverted: true

light:
  - platform: monochromatic
    name: 'light 01'
    output: pwm01
  - platform: monochromatic
    name: 'light 02'
    output: pwm02
  - platform: monochromatic
    name: 'light 03'
    output: pwm03
  - platform: monochromatic
    name: 'light 04'
    output: pwm04
  - platform: monochromatic
    name: 'light 05'
    output: pwm05
  - platform: monochromatic
    name: 'light 06'
    output: pwm06
  - platform: monochromatic
    name: 'light 07'
    output: pwm07
  - platform: monochromatic
    name: 'light 08'
    output: pwm08
  - platform: monochromatic
    name: 'light 09'
    output: pwm09
  - platform: monochromatic
    name: 'light 10'
    output: pwm10
  - platform: monochromatic
    name: 'light 11'
    output: pwm11
  - platform: monochromatic
    name: 'light 12'
    output: pwm12
  - platform: monochromatic
    name: 'light 13'
    output: pwm13
  - platform: monochromatic
    name: 'light 14'
    output: pwm14
  - platform: monochromatic
    name: 'light 15'
    output: pwm15
  - platform: monochromatic
    name: 'light 16'
    output: pwm16

  - platform: binary
    name: "Led"
    output: led_output

binary_sensor:
  - platform: gpio
    pin: D6
    name: "Sensor 1"
    id: moving1
    device_class: MOTION
    on_press:
      then:
        - 

  - platform: gpio
    pin: D7
    name: "Sensor 2"    
    id: moving2
    device_class: MOTION
  
number:
  - platform: template
    name: "Яркость"
    optimistic: true
    min_value: 0
    max_value: 255
    step: 1
    restore_value: true
    initial_value: 255
  
  - platform: template
    name: "Задержка между ступенями"
    optimistic: true
    min_value: 0
    max_value: 30
    step: 0.1
    restore_value: true
    initial_value: 1

  - platform: template
    name: "Макс. время прохода"
    optimistic: true
    min_value: 0
    max_value: 600
    step: 1        
    restore_value: true
    initial_value: 60
